// <auto-generated />
namespace Broadway._6PM.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class referenceToUserInVendor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(referenceToUserInVendor));
        
        string IMigrationMetadata.Id
        {
            get { return "202107271230097_referenceToUserInVendor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
