// <auto-generated />
namespace Broadway._6PM.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class imageresource : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageresource));
        
        string IMigrationMetadata.Id
        {
            get { return "202108061236477_imageresource"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
