// <auto-generated />
namespace Broadway._6PM.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class requiredFieldApplied : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredFieldApplied));
        
        string IMigrationMetadata.Id
        {
            get { return "202107251253089_requiredFieldApplied"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
